# Generated by Django 5.2.3 on 2025-06-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('hamster', 'Hámster'), ('ave', 'Ave')], max_length=30)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=2)),
                ('No', models.BooleanField(verbose_name='Si')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('vacunacion', 'Vacunacion')], max_length=20)),
                ('veterinario', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pepe.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('atención_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pepe.atencionmedica')),
                ('diagnostico', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
            ],
            bases=('pepe.atencionmedica',),
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('atención_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pepe.atencionmedica')),
                ('vacuna', models.CharField(choices=[('anti-rabia', 'Anti-Rabia'), ('anti-leucemia_felina', 'Anti-leucemia_felina'), ('anti-tifoidea', 'Anti-tifoidea'), ('anti-viruela', 'Anti-viruela')], max_length=100)),
            ],
            bases=('pepe.atencionmedica',),
        ),
    ]
