# Generated by Django 5.2.3 on 2025-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='No',
        ),
        migrations.AddField(
            model_name='animal',
            name='disp_adopcion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='atencionmedica',
            name='veterinario',
            field=models.CharField(choices=[('dr_andres_herrera', 'Dr. Andrés Herrera'), ('dra_clara_nuñez', 'Dra. Clara Núñez'), ('dra_sofia_mena', 'Dra. Sofía Mena'), ('dr_luis_torres', 'Dr. Luis Torres')], max_length=30),
        ),
    ]
